-- PostgreSQL DDL converted from MySQL for database: al_server_ls
-- Generated by migrate_sql.js

SET client_encoding = 'UTF8';


-- Table structure for account_data
DROP TABLE IF EXISTS account_data CASCADE;
CREATE TABLE account_data (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  name varchar(45) NOT NULL,
  password varchar(65) NOT NULL,
  activated SMALLINT NOT NULL DEFAULT '1',
  access_level SMALLINT NOT NULL DEFAULT '5',
  membership SMALLINT NOT NULL DEFAULT '0',
  old_membership SMALLINT NOT NULL DEFAULT '0',
  last_server SMALLINT NOT NULL DEFAULT '-1',
  last_ip varchar(20) DEFAULT NULL,
  last_mac varchar(20) NOT NULL DEFAULT 'xx-xx-xx-xx-xx-xx',
  ip_force varchar(20) DEFAULT NULL,
  expire date DEFAULT NULL,
  toll BIGINT NOT NULL DEFAULT '0',
  email varchar(50) DEFAULT NULL,
  question varchar(50) DEFAULT NULL,
  answer varchar(50) DEFAULT NULL,
  balance REAL NOT NULL DEFAULT '0',
  luna INTEGER NOT NULL DEFAULT '0',
  return_account SMALLINT NOT NULL DEFAULT '0',
  return_end timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX account_data_name ON account_data(name);


-- Table structure for account_playtime
DROP TABLE IF EXISTS account_playtime CASCADE;
CREATE TABLE account_playtime (
  account_id INTEGER NOT NULL,
  accumulated_online INTEGER NOT NULL DEFAULT '0',
  lastupdate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (account_id)
);


-- Table structure for account_rewards
DROP TABLE IF EXISTS account_rewards CASCADE;
CREATE TABLE account_rewards (
  uniqId INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  accountId INTEGER NOT NULL,
  added varchar(70) NOT NULL DEFAULT '',
  points decimal(20,0) NOT NULL DEFAULT '0',
  received varchar(70) NOT NULL DEFAULT '0',
  rewarded SMALLINT NOT NULL DEFAULT '0',
  luna decimal(20,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (uniqId)
);

CREATE INDEX idx_account_rewards_FK_account_rewards ON account_rewards(accountId);


-- Table structure for account_time
DROP TABLE IF EXISTS account_time CASCADE;
CREATE TABLE account_time (
  account_id INTEGER NOT NULL,
  last_active timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expiration_time timestamp NULL DEFAULT NULL,
  session_duration INTEGER DEFAULT '0',
  accumulated_online INTEGER DEFAULT '0',
  accumulated_rest INTEGER DEFAULT '0',
  penalty_end timestamp NULL DEFAULT NULL,
  PRIMARY KEY (account_id)
);


-- Table structure for banned_ip
DROP TABLE IF EXISTS banned_ip CASCADE;
CREATE TABLE banned_ip (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  mask varchar(45) NOT NULL,
  time_end timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX banned_ip_mask ON banned_ip(mask);


-- Table structure for banned_mac
DROP TABLE IF EXISTS banned_mac CASCADE;
CREATE TABLE banned_mac (
  uniId INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  address varchar(20) NOT NULL UNIQUE,
  "time" timestamp NOT NULL DEFAULT '1970-01-01 00:00:00',
  details varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (uniId)
);


-- Table structure for gameservers
DROP TABLE IF EXISTS gameservers CASCADE;
CREATE TABLE gameservers (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  mask varchar(45) NOT NULL,
  password varchar(65) NOT NULL,
  PRIMARY KEY (id)
);


-- Records of gameservers

-- Table structure for player_transfers
DROP TABLE IF EXISTS player_transfers CASCADE;
CREATE TABLE player_transfers (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  source_server SMALLINT NOT NULL,
  target_server SMALLINT NOT NULL,
  source_account_id INTEGER NOT NULL,
  target_account_id INTEGER NOT NULL,
  player_id INTEGER NOT NULL,
  status SMALLINT NOT NULL DEFAULT '0',
  time_added varchar(100) DEFAULT NULL,
  time_performed varchar(100) DEFAULT NULL,
  time_done varchar(100) DEFAULT NULL,
  comment TEXT,
  PRIMARY KEY (id)
);


-- Records of player_transfers

-- Table structure for svstats
DROP TABLE IF EXISTS svstats CASCADE;
CREATE TABLE svstats (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  server INTEGER NOT NULL DEFAULT '0',
  status INTEGER NOT NULL DEFAULT '0',
  current INTEGER NOT NULL DEFAULT '0',
  max INTEGER NOT NULL DEFAULT '0',
  last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);


-- Records of svstats

-- Table structure for tasks
DROP TABLE IF EXISTS tasks CASCADE;
CREATE TABLE tasks (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  task_type VARCHAR(50) CHECK (task_type IN ('SHUTDOWN','RESTART','CLEAN_ACCOUNTS')) NOT NULL,
  trigger_type VARCHAR(50) CHECK (trigger_type IN ('FIXED_IN_TIME','AFTER_RESTART')) NOT NULL,
  exec_param TEXT,
  trigger_param TEXT NOT NULL,
  PRIMARY KEY (id)
);


-- Records of tasks