-- PostgreSQL DDL converted from MySQL for database: al_server_gs
-- Generated by migrate_sql.js

SET client_encoding = 'UTF8';


-- Table structure for abyss_landing
DROP TABLE IF EXISTS abyss_landing CASCADE;
CREATE TABLE abyss_landing (
  id INTEGER NOT NULL,
  level INTEGER NOT NULL DEFAULT '1',
  points INTEGER NOT NULL DEFAULT '0',
  siege INTEGER NOT NULL DEFAULT '0',
  commander INTEGER NOT NULL DEFAULT '0',
  artefact INTEGER NOT NULL DEFAULT '0',
  base INTEGER NOT NULL DEFAULT '0',
  monuments INTEGER NOT NULL DEFAULT '0',
  quest INTEGER NOT NULL DEFAULT '0',
  facility INTEGER NOT NULL DEFAULT '0',
  race VARCHAR(50) CHECK (race IN ('ELYOS','ASMODIANS')) NOT NULL,
  level_up_date timestamp NOT NULL DEFAULT '2015-01-01 01:00:00',
  PRIMARY KEY (id)
);


-- Table structure for abyss_rank
DROP TABLE IF EXISTS abyss_rank CASCADE;
CREATE TABLE abyss_rank (
  player_id INTEGER NOT NULL,
  daily_ap INTEGER NOT NULL,
  daily_gp INTEGER NOT NULL,
  weekly_ap INTEGER NOT NULL,
  weekly_gp INTEGER NOT NULL,
  ap INTEGER NOT NULL,
  gp INTEGER NOT NULL,
  rank INTEGER NOT NULL DEFAULT '1',
  top_ranking INTEGER NOT NULL,
  daily_kill INTEGER NOT NULL,
  weekly_kill INTEGER NOT NULL,
  all_kill INTEGER NOT NULL DEFAULT '0',
  max_rank INTEGER NOT NULL DEFAULT '1',
  last_kill INTEGER NOT NULL,
  last_ap INTEGER NOT NULL,
  last_gp INTEGER NOT NULL,
  last_update decimal(20,0) NOT NULL,
  rank_pos INTEGER NOT NULL DEFAULT '0',
  old_rank_pos INTEGER NOT NULL DEFAULT '0',
  rank_ap INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (player_id)
);


-- Table structure for account_balance
DROP TABLE IF EXISTS account_balance CASCADE;
CREATE TABLE account_balance (
  account_id INTEGER NOT NULL,
  price_id INTEGER NOT NULL DEFAULT '0',
  value INTEGER DEFAULT '0',
  PRIMARY KEY (account_id, price_id)
);


-- Table structure for announcements
DROP TABLE IF EXISTS announcements CASCADE;
CREATE TABLE announcements (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  announce TEXT NOT NULL,
  faction VARCHAR(50) CHECK (faction IN ('ALL','ASMODIANS','ELYOS')) NOT NULL DEFAULT 'ALL',
  type VARCHAR(50) CHECK (type IN ('SHOUT','ORANGE','YELLOW','WHITE','SYSTEM')) NOT NULL DEFAULT 'SYSTEM',
  delay INTEGER NOT NULL DEFAULT '1800',
  PRIMARY KEY (id)
);


-- Table structure for banned_hdd
DROP TABLE IF EXISTS banned_hdd CASCADE;
CREATE TABLE banned_hdd (
  uniId INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  hdd_serial varchar(50) NOT NULL,
  "time" timestamp NOT NULL DEFAULT '1970-01-01 00:00:00',
  details varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (uniId)
);


-- Table structure for base_location
DROP TABLE IF EXISTS base_location CASCADE;
CREATE TABLE base_location (
  id INTEGER NOT NULL,
  race VARCHAR(50) CHECK (race IN ('ELYOS','ASMODIANS','NPC')) NOT NULL,
  PRIMARY KEY (id)
);


-- Table structure for blocks
DROP TABLE IF EXISTS blocks CASCADE;
CREATE TABLE blocks (
  player INTEGER NOT NULL,
  blocked_player INTEGER NOT NULL,
  reason varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (player, blocked_player)
);

CREATE INDEX idx_blocks_blocked_player ON blocks(blocked_player);


-- Table structure for bookmark
DROP TABLE IF EXISTS bookmark CASCADE;
CREATE TABLE bookmark (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  name varchar(50) DEFAULT NULL,
  char_id INTEGER NOT NULL,
  x REAL NOT NULL,
  y REAL NOT NULL,
  z REAL NOT NULL,
  world_id INTEGER NOT NULL,
  PRIMARY KEY (id)
);


-- Table structure for broker
DROP TABLE IF EXISTS broker CASCADE;
CREATE TABLE broker (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  item_pointer INTEGER NOT NULL DEFAULT '0',
  item_id INTEGER NOT NULL,
  item_count BIGINT NOT NULL,
  item_creator varchar(50) DEFAULT NULL,
  seller varchar(50) DEFAULT NULL,
  price BIGINT NOT NULL DEFAULT '0',
  broker_race VARCHAR(50) CHECK (broker_race IN ('ELYOS','ASMODIAN')) NOT NULL,
  expire_time timestamp NOT NULL DEFAULT '2010-01-01 14:00:00',
  settle_time timestamp NOT NULL DEFAULT '2010-01-01 14:00:00',
  seller_id INTEGER NOT NULL,
  is_sold SMALLINT NOT NULL,
  is_settled SMALLINT NOT NULL,
  is_splitsell SMALLINT NOT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX idx_broker_seller_id ON broker(seller_id);


-- Table structure for challenge_tasks
DROP TABLE IF EXISTS challenge_tasks CASCADE;
CREATE TABLE challenge_tasks (
  task_id INTEGER NOT NULL,
  quest_id INTEGER NOT NULL,
  owner_id INTEGER NOT NULL,
  owner_type VARCHAR(50) CHECK (owner_type IN ('LEGION','TOWN')) NOT NULL,
  complete_count INTEGER NOT NULL DEFAULT '0',
  complete_time timestamp NULL DEFAULT NULL,
  PRIMARY KEY (task_id, quest_id, owner_id, owner_type)
);


-- Table structure for competition_ranking
CREATE TABLE competition_ranking (
  player_id INTEGER NOT NULL,
  table_id INTEGER NOT NULL,
  rank INTEGER NOT NULL DEFAULT '0',
  last_rank INTEGER NOT NULL DEFAULT '0',
  points INTEGER NOT NULL DEFAULT '0',
  last_points INTEGER NOT NULL DEFAULT '0',
  high_points INTEGER NOT NULL DEFAULT '0',
  low_points INTEGER NOT NULL DEFAULT '0',
  position_match INTEGER NOT NULL DEFAULT '5'
);


-- Table structure for craft_cooldowns
DROP TABLE IF EXISTS craft_cooldowns CASCADE;
CREATE TABLE craft_cooldowns (
  player_id INTEGER NOT NULL,
  delay_id INTEGER NOT NULL,
  reuse_time BIGINT NOT NULL,
  PRIMARY KEY (player_id, delay_id)
);


-- Table structure for event_items
DROP TABLE IF EXISTS event_items CASCADE;
CREATE TABLE event_items (
  player_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  counts INTEGER NOT NULL,
  PRIMARY KEY (player_id, item_id)
);


-- Table structure for f2paccount
DROP TABLE IF EXISTS f2paccount CASCADE;
CREATE TABLE f2paccount (
  player_id INTEGER NOT NULL,
  "time" INTEGER NOT NULL,
  PRIMARY KEY (player_id)
);


-- Table structure for friends
DROP TABLE IF EXISTS friends CASCADE;
CREATE TABLE friends (
  player INTEGER NOT NULL,
  friend INTEGER NOT NULL,
  PRIMARY KEY (player, friend)
);

CREATE INDEX idx_friends_friend ON friends(friend);


-- Table structure for guides
DROP TABLE IF EXISTS guides CASCADE;
CREATE TABLE guides (
  guide_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  player_id INTEGER NOT NULL,
  title varchar(80) NOT NULL,
  PRIMARY KEY (guide_id)
);

CREATE INDEX idx_guides_player_id ON guides(player_id);


-- Table structure for houses
DROP TABLE IF EXISTS houses CASCADE;
CREATE TABLE houses (
  id INTEGER NOT NULL,
  player_id INTEGER NOT NULL DEFAULT '0',
  building_id INTEGER NOT NULL,
  address INTEGER NOT NULL,
  acquire_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  settings INTEGER NOT NULL DEFAULT '0',
  status VARCHAR(50) CHECK (status IN ('ACTIVE','SELL_WAIT','INACTIVE','NOSALE')) NOT NULL DEFAULT 'ACTIVE',
  fee_paid SMALLINT NOT NULL DEFAULT '1',
  next_pay timestamp NULL DEFAULT NULL,
  sell_started timestamp NULL DEFAULT NULL,
  sign_notice BYTEA DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX idx_houses_address ON houses(address);


-- Table structure for house_bids
DROP TABLE IF EXISTS house_bids CASCADE;
CREATE TABLE house_bids (
  player_id INTEGER NOT NULL,
  house_id INTEGER NOT NULL,
  bid BIGINT NOT NULL,
  bid_time timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (player_id, house_id, bid)
);

CREATE INDEX idx_house_bids_house_id_ibfk_1 ON house_bids(house_id);


-- Table structure for house_object_cooldowns
DROP TABLE IF EXISTS house_object_cooldowns CASCADE;
CREATE TABLE house_object_cooldowns (
  player_id INTEGER NOT NULL,
  object_id INTEGER NOT NULL,
  reuse_time BIGINT NOT NULL,
  PRIMARY KEY (player_id, object_id)
);


-- Table structure for house_scripts
DROP TABLE IF EXISTS house_scripts CASCADE;
CREATE TABLE house_scripts (
  house_id INTEGER NOT NULL,
  "index" SMALLINT NOT NULL,
  script TEXT,
  PRIMARY KEY (house_id, index)
);


-- Table structure for ingameshop
DROP TABLE IF EXISTS ingameshop CASCADE;
CREATE TABLE ingameshop (
  object_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  item_id INTEGER NOT NULL,
  item_count BIGINT NOT NULL DEFAULT '0',
  item_price BIGINT NOT NULL DEFAULT '0',
  category SMALLINT NOT NULL DEFAULT '0',
  sub_category SMALLINT NOT NULL DEFAULT '0',
  list INTEGER NOT NULL DEFAULT '0',
  sales_ranking INTEGER NOT NULL DEFAULT '0',
  item_type SMALLINT NOT NULL DEFAULT '0',
  gift SMALLINT NOT NULL DEFAULT '0',
  title_description varchar(255) NOT NULL,
  description varchar(255) NOT NULL,
  PRIMARY KEY (object_id)
);


-- Table structure for inventory
DROP TABLE IF EXISTS inventory CASCADE;
CREATE TABLE inventory (
  item_unique_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  item_count BIGINT NOT NULL DEFAULT '0',
  item_color INTEGER NOT NULL DEFAULT '0',
  color_expires INTEGER DEFAULT NULL,
  item_owner INTEGER NOT NULL,
  item_creator varchar(50) DEFAULT NULL,
  itemCreationTime timestamp NOT NULL DEFAULT '2013-01-01 12:00:01',
  expire_time INTEGER NOT NULL DEFAULT '0',
  is_equiped SMALLINT NOT NULL DEFAULT '0',
  is_soul_bound SMALLINT NOT NULL DEFAULT '0',
  slot BIGINT NOT NULL DEFAULT '0',
  item_location SMALLINT DEFAULT '0',
  enchant SMALLINT DEFAULT '0',
  enchant_bonus INTEGER NOT NULL DEFAULT '0',
  item_skin INTEGER NOT NULL DEFAULT '0',
  fusioned_item INTEGER NOT NULL DEFAULT '0',
  optional_socket INTEGER NOT NULL DEFAULT '0',
  optional_fusion_socket INTEGER NOT NULL DEFAULT '0',
  activation_count INTEGER NOT NULL DEFAULT '0',
  charge INTEGER NOT NULL DEFAULT '0',
  rnd_bonus SMALLINT DEFAULT NULL,
  rnd_count SMALLINT NOT NULL DEFAULT '0',
  wrappable_count SMALLINT NOT NULL DEFAULT '0',
  is_packed SMALLINT NOT NULL DEFAULT '0',
  tempering_level SMALLINT NOT NULL DEFAULT '0',
  is_topped SMALLINT NOT NULL DEFAULT '0',
  strengthen_skill INTEGER NOT NULL DEFAULT '0',
  skin_skill INTEGER DEFAULT '0',
  luna_reskin SMALLINT NOT NULL DEFAULT '0',
  reduction_level INTEGER NOT NULL DEFAULT '0',
  is_seal INTEGER NOT NULL DEFAULT '0',
  isEnhance SMALLINT DEFAULT '0',
  enhanceSkillId INTEGER NOT NULL DEFAULT '0',
  enhanceSkillEnchant INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (item_unique_id)
);

CREATE INDEX idx_inventory_item_owner ON inventory(item_owner);
CREATE INDEX idx_inventory_item_location ON inventory(item_location);
CREATE INDEX idx_inventory_is_equiped ON inventory(is_equiped);


-- Table structure for item_cooldowns
DROP TABLE IF EXISTS item_cooldowns CASCADE;
CREATE TABLE item_cooldowns (
  player_id INTEGER NOT NULL,
  delay_id INTEGER NOT NULL,
  use_delay INTEGER NOT NULL,
  reuse_time BIGINT NOT NULL,
  PRIMARY KEY (player_id, delay_id)
);


-- Table structure for item_drop
DROP TABLE IF EXISTS item_drop CASCADE;
CREATE TABLE item_drop (
  npc_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL DEFAULT '0',
  drop_group varchar(255) DEFAULT NULL,
  race VARCHAR(50) CHECK (race IN ('PC_ALL','ELYOS','ASMODIANS')) DEFAULT 'PC_ALL',
  min_amount INTEGER NOT NULL DEFAULT '0',
  max_amount INTEGER NOT NULL DEFAULT '0',
  chance decimal(11,0) DEFAULT NULL,
  no_reduce SMALLINT NOT NULL DEFAULT '0',
  eachmember SMALLINT NOT NULL DEFAULT '0'
);


-- Table structure for item_stones
DROP TABLE IF EXISTS item_stones CASCADE;
CREATE TABLE item_stones (
  item_unique_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  slot INTEGER NOT NULL,
  category INTEGER NOT NULL DEFAULT '0',
  polishNumber INTEGER DEFAULT NULL,
  polishCharge INTEGER DEFAULT NULL,
  PRIMARY KEY (item_unique_id, slot, category)
);


-- Table structure for ladder_player
DROP TABLE IF EXISTS ladder_player CASCADE;
CREATE TABLE ladder_player (
  player_id INTEGER NOT NULL,
  rating INTEGER DEFAULT '1000',
  wins INTEGER DEFAULT NULL,
  losses INTEGER DEFAULT NULL,
  leaves INTEGER DEFAULT NULL,
  rank INTEGER NOT NULL DEFAULT '-1',
  last_rank INTEGER NOT NULL DEFAULT '-1',
  last_update timestamp NULL DEFAULT NULL,
  PRIMARY KEY (player_id)
);


-- Table structure for legions
DROP TABLE IF EXISTS legions CASCADE;
CREATE TABLE legions (
  id INTEGER NOT NULL,
  name varchar(32) NOT NULL,
  level INTEGER NOT NULL DEFAULT '1',
  contribution_points BIGINT NOT NULL DEFAULT '0',
  deputy_permission INTEGER NOT NULL DEFAULT '7692',
  centurion_permission INTEGER NOT NULL DEFAULT '7176',
  legionary_permission INTEGER NOT NULL DEFAULT '6144',
  volunteer_permission INTEGER NOT NULL DEFAULT '2048',
  disband_time INTEGER NOT NULL DEFAULT '0',
  rank_cp INTEGER NOT NULL DEFAULT '0',
  rank_pos INTEGER NOT NULL DEFAULT '0',
  old_rank_pos INTEGER NOT NULL DEFAULT '0',
  description varchar(255) NOT NULL DEFAULT '',
  joinType INTEGER NOT NULL DEFAULT '0',
  minJoinLevel INTEGER NOT NULL DEFAULT '0',
  territory INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX legions_name_unique ON legions(name);


-- Table structure for legion_announcement_list
DROP TABLE IF EXISTS legion_announcement_list CASCADE;
CREATE TABLE legion_announcement_list (
  legion_id INTEGER NOT NULL,
  announcement varchar(256) NOT NULL,
  "date" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_legion_announcement_list_legion_id ON legion_announcement_list(legion_id);


-- Table structure for legion_emblems
DROP TABLE IF EXISTS legion_emblems CASCADE;
CREATE TABLE legion_emblems (
  legion_id INTEGER NOT NULL,
  emblem_id INTEGER NOT NULL DEFAULT '0',
  color_r INTEGER NOT NULL DEFAULT '0',
  color_g INTEGER NOT NULL DEFAULT '0',
  color_b INTEGER NOT NULL DEFAULT '0',
  emblem_type VARCHAR(50) CHECK (emblem_type IN ('DEFAULT','CUSTOM')) NOT NULL DEFAULT 'DEFAULT',
  emblem_data BYTEA,
  PRIMARY KEY (legion_id)
);


-- Table structure for legion_history
DROP TABLE IF EXISTS legion_history CASCADE;
CREATE TABLE legion_history (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  legion_id INTEGER NOT NULL,
  "date" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  history_type VARCHAR(50) CHECK (history_type IN ('CREATE','JOIN','KICK','APPOINTED','EMBLEM_REGISTER','EMBLEM_MODIFIED','ITEM_DEPOSIT','ITEM_WITHDRAW','KINAH_DEPOSIT','KINAH_WITHDRAW','LEVEL_UP')) NOT NULL,
  name varchar(50) NOT NULL,
  tab_id SMALLINT NOT NULL DEFAULT '0',
  description varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (id)
);

CREATE INDEX idx_legion_history_legion_id ON legion_history(legion_id);


-- Table structure for legion_join_requests
DROP TABLE IF EXISTS legion_join_requests CASCADE;
CREATE TABLE legion_join_requests (
  legionId INTEGER NOT NULL DEFAULT '0',
  playerId INTEGER NOT NULL DEFAULT '0',
  playerName varchar(64) NOT NULL DEFAULT '',
  playerClassId INTEGER NOT NULL DEFAULT '0',
  playerRaceId INTEGER NOT NULL DEFAULT '0',
  playerLevel INTEGER NOT NULL DEFAULT '0',
  playerGenderId INTEGER NOT NULL DEFAULT '0',
  joinRequestMsg varchar(40) NOT NULL DEFAULT '',
  "date" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (legionId, playerId)
);

CREATE INDEX idx_legion_join_requests_legionId ON legion_join_requests(legionId);
CREATE INDEX idx_legion_join_requests_playerId ON legion_join_requests(playerId);


-- Table structure for legion_members
DROP TABLE IF EXISTS legion_members CASCADE;
CREATE TABLE legion_members (
  legion_id INTEGER NOT NULL,
  player_id INTEGER NOT NULL,
  nickname varchar(10) NOT NULL DEFAULT '',
  rank VARCHAR(50) CHECK (rank IN ('BRIGADE_GENERAL','CENTURION','LEGIONARY','DEPUTY','VOLUNTEER')) NOT NULL DEFAULT 'VOLUNTEER',
  selfintro varchar(32) DEFAULT '',
  challenge_score INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (player_id)
);

CREATE INDEX idx_legion_members_player_id ON legion_members(player_id);
CREATE INDEX idx_legion_members_legion_id ON legion_members(legion_id);


-- Table structure for log_command_add
DROP TABLE IF EXISTS log_command_add CASCADE;
CREATE TABLE log_command_add (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  admin_id INTEGER NOT NULL DEFAULT '0',
  admin_name varchar(255) DEFAULT '',
  player_id INTEGER DEFAULT '0',
  player_name varchar(255) DEFAULT '',
  item_unique INTEGER DEFAULT '0',
  item_id INTEGER DEFAULT '0',
  item_name varchar(255) DEFAULT '',
  item_count varchar(255) DEFAULT '0',
  description varchar(255) DEFAULT '',
  "date" TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (id)
);


-- Table structure for log_exchange_admin
DROP TABLE IF EXISTS log_exchange_admin CASCADE;
CREATE TABLE log_exchange_admin (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  admin_id INTEGER NOT NULL DEFAULT '0',
  admin_name varchar(255) DEFAULT '',
  player_id INTEGER DEFAULT '0',
  player_name varchar(255) DEFAULT '',
  item_id INTEGER DEFAULT '0',
  item_name varchar(255) DEFAULT '',
  item_count varchar(255) DEFAULT '0',
  description varchar(255) DEFAULT '',
  "date" TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (id)
);


-- Table structure for log_exchange_player
DROP TABLE IF EXISTS log_exchange_player CASCADE;
CREATE TABLE log_exchange_player (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  player_id INTEGER NOT NULL DEFAULT '0',
  player_name varchar(255) DEFAULT '',
  partner_id INTEGER DEFAULT '0',
  partner_name varchar(255) DEFAULT '',
  item_id INTEGER DEFAULT '0',
  item_name varchar(255) DEFAULT '',
  item_count varchar(255) DEFAULT '0',
  description varchar(255) DEFAULT '',
  "date" TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (id)
);


-- Table structure for log_mail_admin
DROP TABLE IF EXISTS log_mail_admin CASCADE;
CREATE TABLE log_mail_admin (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  admin_id INTEGER NOT NULL DEFAULT '0',
  admin_name varchar(255) DEFAULT '',
  item_id INTEGER DEFAULT '0',
  item_name varchar(255) DEFAULT '',
  item_count varchar(255) DEFAULT '0',
  player_recive_name varchar(255) DEFAULT '',
  description varchar(255) DEFAULT '',
  "date" TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (id)
);


-- Table structure for log_mail_player
DROP TABLE IF EXISTS log_mail_player CASCADE;
CREATE TABLE log_mail_player (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  sender_id INTEGER NOT NULL DEFAULT '0',
  sender_name varchar(255) DEFAULT '',
  item_id INTEGER DEFAULT '0',
  item_name varchar(255) DEFAULT '',
  item_count varchar(255) DEFAULT '0',
  player_recive_name varchar(255) DEFAULT '',
  description varchar(255) DEFAULT '',
  "date" TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (id)
);


-- Table structure for mail
DROP TABLE IF EXISTS mail CASCADE;
CREATE TABLE mail (
  mail_unique_id INTEGER NOT NULL,
  mail_recipient_id INTEGER NOT NULL,
  sender_name varchar(26) NOT NULL,
  mail_title varchar(20) NOT NULL,
  mail_message varchar(1000) NOT NULL,
  unread SMALLINT NOT NULL DEFAULT '1',
  attached_item_id INTEGER NOT NULL,
  attached_kinah_count BIGINT NOT NULL,
  attached_ap_count BIGINT NOT NULL,
  express SMALLINT NOT NULL DEFAULT '0',
  recieved_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (mail_unique_id)
);

CREATE INDEX idx_mail_mail_recipient_id ON mail(mail_recipient_id);


-- Table structure for network_ban
DROP TABLE IF EXISTS network_ban CASCADE;
CREATE TABLE network_ban (
  uniId INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  ip varchar(50) NOT NULL,
  "time" timestamp NOT NULL DEFAULT '1970-01-01 00:00:00',
  details varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (uniId)
);


-- Table structure for old_names
DROP TABLE IF EXISTS old_names CASCADE;
CREATE TABLE old_names (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  player_id INTEGER NOT NULL,
  old_name varchar(50) NOT NULL,
  new_name varchar(50) NOT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX idx_old_names_player_id ON old_names(player_id);


-- Table structure for outpost_location
CREATE TABLE outpost_location (
  id INTEGER NOT NULL,
  race VARCHAR(50) CHECK (race IN ('ELYOS','ASMODIANS','NPC')) NOT NULL,
  PRIMARY KEY (id)
);


-- Table structure for petitions
DROP TABLE IF EXISTS petitions CASCADE;
CREATE TABLE petitions (
  id BIGINT NOT NULL,
  player_id INTEGER NOT NULL,
  type INTEGER NOT NULL,
  title varchar(255) NOT NULL,
  message TEXT NOT NULL,
  add_data varchar(255) DEFAULT NULL,
  "time" BIGINT NOT NULL DEFAULT '0',
  status VARCHAR(50) CHECK (status IN ('PENDING','IN_PROGRESS','REPLIED')) NOT NULL,
  PRIMARY KEY (id)
);


-- Table structure for players
DROP TABLE IF EXISTS players CASCADE;
CREATE TABLE players (
  id INTEGER NOT NULL,
  name varchar(50) NOT NULL,
  account_id INTEGER NOT NULL,
  account_name varchar(50) NOT NULL,
  exp BIGINT NOT NULL DEFAULT '0',
  recoverexp BIGINT NOT NULL DEFAULT '0',
  x REAL NOT NULL,
  y REAL NOT NULL,
  z REAL NOT NULL,
  heading INTEGER NOT NULL,
  world_id INTEGER NOT NULL,
  gender VARCHAR(50) CHECK (gender IN ('MALE','FEMALE')) NOT NULL,
  race VARCHAR(50) CHECK (race IN ('ASMODIANS','ELYOS')) NOT NULL,
  player_class VARCHAR(50) CHECK (player_class IN ('WARRIOR','GLADIATOR','TEMPLAR','SCOUT','ASSASSIN','RANGER','MAGE','SORCERER','SPIRIT_MASTER','PRIEST','CLERIC','CHANTER','TECHNIST','GUNSLINGER','AETHERTECH','MUSE','SONGWEAVER')) NOT NULL,
  creation_date timestamp NULL DEFAULT NULL,
  deletion_date timestamp NULL DEFAULT NULL,
  last_online timestamp NULL DEFAULT NULL,
  quest_expands SMALLINT NOT NULL DEFAULT '0',
  advenced_stigma_slot_size SMALLINT NOT NULL DEFAULT '0',
  warehouse_size SMALLINT NOT NULL DEFAULT '0',
  mailbox_letters SMALLINT NOT NULL DEFAULT '0',
  bind_point INTEGER NOT NULL DEFAULT '0',
  title_id INTEGER NOT NULL DEFAULT '-1',
  bonus_title_id INTEGER NOT NULL,
  online SMALLINT NOT NULL DEFAULT '0',
  note TEXT,
  npc_expands SMALLINT NOT NULL DEFAULT '0',
  world_owner INTEGER NOT NULL DEFAULT '0',
  dp INTEGER NOT NULL DEFAULT '0',
  soul_sickness SMALLINT NOT NULL DEFAULT '0',
  reposte_energy BIGINT NOT NULL DEFAULT '0',
  mentor_flag_time INTEGER NOT NULL DEFAULT '0',
  last_transfer_time decimal(20,0) NOT NULL DEFAULT '0',
  stamps INTEGER NOT NULL DEFAULT '0',
  last_stamp timestamp NOT NULL DEFAULT '2015-01-01 12:00:00',
  rewarded_pass INTEGER NOT NULL DEFAULT '0',
  passport_time BIGINT NOT NULL DEFAULT '0',
  is_archdaeva SMALLINT NOT NULL,
  creativity_point INTEGER NOT NULL DEFAULT '0',
  aura_of_growth BIGINT NOT NULL DEFAULT '0',
  join_legion_id INTEGER NOT NULL DEFAULT '0',
  join_state VARCHAR(50) CHECK (join_state IN ('NONE','DENIED','ACCEPTED')) NOT NULL DEFAULT 'NONE',
  berdin_star BIGINT NOT NULL DEFAULT '0',
  luna_consume INTEGER NOT NULL DEFAULT '0',
  muni_keys INTEGER NOT NULL DEFAULT '0',
  luna_consume_count INTEGER NOT NULL DEFAULT '0',
  wardrobe_slot INTEGER NOT NULL DEFAULT '2',
  abyss_favor BIGINT DEFAULT '0',
  luna_points INTEGER DEFAULT '0',
  frenzy_points INTEGER DEFAULT '0',
  frenzy_count INTEGER DEFAULT '0',
  toc_floor INTEGER DEFAULT '0',
  stone_cp INTEGER NOT NULL DEFAULT '0',
  golden_dice INTEGER NOT NULL DEFAULT '0',
  sweep_reset INTEGER NOT NULL DEFAULT '0',
  minion_skill_points INTEGER NOT NULL DEFAULT '0',
  minion_function_time timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX players_name_unique ON players(name);
CREATE INDEX idx_players_account_id ON players(account_id);


-- Table structure for player_appearance
DROP TABLE IF EXISTS player_appearance CASCADE;
CREATE TABLE player_appearance (
  player_id INTEGER NOT NULL,
  voice INTEGER NOT NULL,
  skin_rgb INTEGER NOT NULL,
  hair_rgb INTEGER NOT NULL,
  eye_rgb INTEGER NOT NULL,
  lip_rgb INTEGER NOT NULL,
  face INTEGER NOT NULL,
  hair INTEGER NOT NULL,
  deco INTEGER NOT NULL,
  tattoo INTEGER NOT NULL,
  face_contour INTEGER NOT NULL,
  expression INTEGER NOT NULL,
  pupil_shape INTEGER NOT NULL,
  remove_mane INTEGER NOT NULL,
  right_eye_rgb INTEGER NOT NULL,
  eye_lash_shape INTEGER NOT NULL,
  jaw_line INTEGER NOT NULL,
  forehead INTEGER NOT NULL,
  eye_height INTEGER NOT NULL,
  eye_space INTEGER NOT NULL,
  eye_width INTEGER NOT NULL,
  eye_size INTEGER NOT NULL,
  eye_shape INTEGER NOT NULL,
  eye_angle INTEGER NOT NULL,
  brow_height INTEGER NOT NULL,
  brow_angle INTEGER NOT NULL,
  brow_shape INTEGER NOT NULL,
  nose INTEGER NOT NULL,
  nose_bridge INTEGER NOT NULL,
  nose_width INTEGER NOT NULL,
  nose_tip INTEGER NOT NULL,
  cheek INTEGER NOT NULL,
  lip_height INTEGER NOT NULL,
  mouth_size INTEGER NOT NULL,
  lip_size INTEGER NOT NULL,
  smile INTEGER NOT NULL,
  lip_shape INTEGER NOT NULL,
  jaw_height INTEGER NOT NULL,
  chin_jut INTEGER NOT NULL,
  ear_shape INTEGER NOT NULL,
  head_size INTEGER NOT NULL,
  neck INTEGER NOT NULL,
  neck_length INTEGER NOT NULL,
  shoulder_size INTEGER NOT NULL,
  torso INTEGER NOT NULL,
  chest INTEGER NOT NULL,
  waist INTEGER NOT NULL,
  hips INTEGER NOT NULL,
  arm_thickness INTEGER NOT NULL,
  hand_size INTEGER NOT NULL,
  leg_thickness INTEGER NOT NULL,
  facial_rate INTEGER NOT NULL,
  foot_size INTEGER NOT NULL,
  arm_length INTEGER NOT NULL,
  leg_length INTEGER NOT NULL,
  shoulders INTEGER NOT NULL,
  face_shape INTEGER NOT NULL,
  pupil_size INTEGER NOT NULL,
  upper_torso INTEGER NOT NULL,
  fore_arm_thickness INTEGER NOT NULL,
  hand_span INTEGER NOT NULL,
  calf_thickness INTEGER NOT NULL,
  height REAL NOT NULL,
  PRIMARY KEY (player_id)
);


-- Table structure for player_atreian_bestiary
CREATE TABLE player_atreian_bestiary (
  player_id INTEGER NOT NULL,
  id INTEGER NOT NULL,
  kill_count INTEGER NOT NULL,
  level INTEGER NOT NULL,
  claim_reward INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (player_id, id)
);


-- Table structure for player_bind_point
DROP TABLE IF EXISTS player_bind_point CASCADE;
CREATE TABLE player_bind_point (
  player_id INTEGER NOT NULL,
  map_id INTEGER NOT NULL,
  x REAL NOT NULL,
  y REAL NOT NULL,
  z REAL NOT NULL,
  heading INTEGER NOT NULL,
  PRIMARY KEY (player_id)
);


-- Table structure for player_combat_points
DROP TABLE IF EXISTS player_combat_points CASCADE;
CREATE TABLE player_combat_points (
  player_id INTEGER NOT NULL,
  slot_id INTEGER NOT NULL,
  cp_point INTEGER NOT NULL DEFAULT '1',
  category varchar(255) DEFAULT NULL,
  PRIMARY KEY (player_id, slot_id)
);


-- Table structure for player_cooldowns
DROP TABLE IF EXISTS player_cooldowns CASCADE;
CREATE TABLE player_cooldowns (
  player_id INTEGER NOT NULL,
  cooldown_id INTEGER NOT NULL,
  reuse_delay BIGINT NOT NULL,
  PRIMARY KEY (player_id, cooldown_id)
);


-- Table structure for player_cp
DROP TABLE IF EXISTS player_cp CASCADE;
CREATE TABLE player_cp (
  player_id INTEGER NOT NULL,
  slot INTEGER NOT NULL,
  point INTEGER NOT NULL,
  PRIMARY KEY (player_id, slot)
);


-- Table structure for player_effects
DROP TABLE IF EXISTS player_effects CASCADE;
CREATE TABLE player_effects (
  player_id INTEGER NOT NULL,
  skill_id INTEGER NOT NULL,
  skill_lvl SMALLINT NOT NULL,
  "current_time" INTEGER NOT NULL,
  end_time BIGINT NOT NULL,
  PRIMARY KEY (player_id, skill_id)
);


-- Table structure for player_emotions
DROP TABLE IF EXISTS player_emotions CASCADE;
CREATE TABLE player_emotions (
  player_id INTEGER NOT NULL,
  emotion INTEGER NOT NULL,
  remaining INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (player_id, emotion)
);


-- Table structure for player_equipment_setting
DROP TABLE IF EXISTS player_equipment_setting CASCADE;
CREATE TABLE player_equipment_setting (
  player_id INTEGER NOT NULL,
  slot INTEGER NOT NULL,
  name varchar(225) NOT NULL,
  display INTEGER NOT NULL DEFAULT '0',
  m_hand INTEGER NOT NULL DEFAULT '0',
  s_hand INTEGER NOT NULL DEFAULT '0',
  helmet INTEGER NOT NULL DEFAULT '0',
  torso INTEGER NOT NULL DEFAULT '0',
  glove INTEGER NOT NULL DEFAULT '0',
  boots INTEGER NOT NULL DEFAULT '0',
  earrings_left INTEGER NOT NULL DEFAULT '0',
  earrings_right INTEGER NOT NULL DEFAULT '0',
  ring_left INTEGER NOT NULL DEFAULT '0',
  ring_right INTEGER NOT NULL DEFAULT '0',
  necklace INTEGER NOT NULL DEFAULT '0',
  shoulder INTEGER NOT NULL DEFAULT '0',
  pants INTEGER NOT NULL DEFAULT '0',
  powershard_left INTEGER NOT NULL DEFAULT '0',
  powershard_right INTEGER NOT NULL DEFAULT '0',
  wings INTEGER NOT NULL DEFAULT '0',
  waist INTEGER NOT NULL DEFAULT '0',
  m_off_hand INTEGER NOT NULL DEFAULT '0',
  s_off_hand INTEGER NOT NULL DEFAULT '0',
  plume INTEGER NOT NULL DEFAULT '0',
  bracelet INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (player_id, slot)
);


-- Table structure for player_events_window
DROP TABLE IF EXISTS player_events_window CASCADE;
CREATE TABLE player_events_window (
  account_id INTEGER NOT NULL,
  event_id INTEGER NOT NULL,
  last_stamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  elapsed INTEGER NOT NULL DEFAULT '0',
  reward_recived_count INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (account_id, event_id)
);


-- Table structure for player_event_cooldowns
DROP TABLE IF EXISTS player_event_cooldowns CASCADE;
CREATE TABLE player_event_cooldowns (
  player_id INTEGER NOT NULL,
  event_id INTEGER NOT NULL,
  count INTEGER NOT NULL,
  mac_address varchar(20) NOT NULL DEFAULT 'xx-xx-xx-xx-xx-xx',
  ip_address varchar(20) DEFAULT NULL,
  next_use decimal(20,0) NOT NULL,
  PRIMARY KEY (player_id)
);


-- Table structure for player_game_stats
DROP TABLE IF EXISTS player_game_stats CASCADE;
CREATE TABLE player_game_stats (
  player_id INTEGER NOT NULL,
  defense_physic INTEGER NOT NULL DEFAULT '1',
  block INTEGER NOT NULL DEFAULT '1',
  parry INTEGER NOT NULL DEFAULT '1',
  magical_critical INTEGER NOT NULL DEFAULT '1',
  evasion INTEGER NOT NULL DEFAULT '1',
  precision INTEGER NOT NULL DEFAULT '1',
  attack INTEGER NOT NULL DEFAULT '1',
  magical_precision INTEGER NOT NULL DEFAULT '1',
  attack_speed INTEGER NOT NULL DEFAULT '1',
  magical_resist INTEGER NOT NULL DEFAULT '1',
  magical_attack INTEGER NOT NULL DEFAULT '1',
  main_hand_magical_attack INTEGER NOT NULL DEFAULT '1',
  off_hand_magical_attack INTEGER NOT NULL DEFAULT '1',
  physical_critical INTEGER NOT NULL DEFAULT '1',
  attack_range INTEGER NOT NULL DEFAULT '1',
  magical_defense INTEGER NOT NULL DEFAULT '1',
  agility INTEGER NOT NULL DEFAULT '1',
  knowledge INTEGER NOT NULL DEFAULT '1',
  will INTEGER NOT NULL DEFAULT '1',
  magical_boost INTEGER NOT NULL DEFAULT '1',
  magical_boost_resist INTEGER NOT NULL DEFAULT '1',
  physical_critical_resist INTEGER NOT NULL DEFAULT '1',
  magical_critical_resist INTEGER NOT NULL DEFAULT '1',
  PRIMARY KEY (player_id)
);


-- Table structure for player_ladder
DROP TABLE IF EXISTS player_ladder CASCADE;
CREATE TABLE player_ladder (
  player_id INTEGER NOT NULL,
  event_id INTEGER NOT NULL DEFAULT '0',
  race varchar(255) DEFAULT NULL,
  class varchar(255) DEFAULT NULL,
  kill INTEGER DEFAULT '0',
  dead INTEGER DEFAULT '0',
  PRIMARY KEY (player_id, event_id)
);


-- Table structure for player_life_stats
DROP TABLE IF EXISTS player_life_stats CASCADE;
CREATE TABLE player_life_stats (
  player_id INTEGER NOT NULL,
  hp INTEGER NOT NULL DEFAULT '1',
  mp INTEGER NOT NULL DEFAULT '1',
  fp INTEGER NOT NULL DEFAULT '1',
  PRIMARY KEY (player_id)
);


-- Table structure for player_luna_shop
DROP TABLE IF EXISTS player_luna_shop CASCADE;
CREATE TABLE player_luna_shop (
  player_id INTEGER NOT NULL,
  free_under SMALLINT NOT NULL,
  free_munition SMALLINT NOT NULL,
  free_chest SMALLINT NOT NULL
);


-- Table structure for player_macrosses
DROP TABLE IF EXISTS player_macrosses CASCADE;
CREATE TABLE player_macrosses (
  player_id INTEGER NOT NULL,
  "order" INTEGER NOT NULL,
  macro TEXT NOT NULL
);

CREATE UNIQUE INDEX player_macrosses_main ON player_macrosses(player_id, "order");


-- Table structure for `player_minions`
DROP TABLE IF EXISTS player_minions CASCADE;
CREATE TABLE player_minions (
  player_id INTEGER NOT NULL,
  object_id INTEGER NOT NULL DEFAULT '0',
  minion_id INTEGER NOT NULL,
  name varchar(255) NOT NULL,
  grade varchar(11) NOT NULL,
  level varchar(11) NOT NULL,
  birthday timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  growthpoints INTEGER NOT NULL DEFAULT '0',
  is_locked INTEGER NOT NULL DEFAULT '0',
  buff_bag VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (player_id, object_id)
);


-- Table structure for player_monsterbook
DROP TABLE IF EXISTS player_monsterbook CASCADE;
CREATE TABLE player_monsterbook (
  player_id INTEGER NOT NULL,
  id INTEGER NOT NULL,
  kill_count INTEGER NOT NULL,
  level INTEGER NOT NULL,
  claim_reward INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (player_id, id)
);


-- Table structure for player_motions
DROP TABLE IF EXISTS player_motions CASCADE;
CREATE TABLE player_motions (
  player_id INTEGER NOT NULL,
  motion_id INTEGER NOT NULL,
  "time" INTEGER NOT NULL DEFAULT '0',
  active SMALLINT NOT NULL DEFAULT '0',
  PRIMARY KEY (player_id, motion_id)
);


-- Table structure for player_npc_factions
DROP TABLE IF EXISTS player_npc_factions CASCADE;
CREATE TABLE player_npc_factions (
  player_id INTEGER NOT NULL,
  faction_id INTEGER NOT NULL,
  active SMALLINT NOT NULL,
  "time" INTEGER NOT NULL,
  state VARCHAR(50) CHECK (state IN ('NOTING','START','COMPLETE')) NOT NULL DEFAULT 'NOTING',
  quest_id INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (player_id, faction_id)
);


-- Table structure for player_passkey
DROP TABLE IF EXISTS player_passkey CASCADE;
CREATE TABLE player_passkey (
  account_id INTEGER NOT NULL,
  passkey varchar(65) NOT NULL,
  PRIMARY KEY (account_id, passkey)
);


-- Table structure for player_passports
DROP TABLE IF EXISTS player_passports CASCADE;
CREATE TABLE player_passports (
  account_id INTEGER NOT NULL,
  passport_id INTEGER NOT NULL,
  stamps INTEGER NOT NULL DEFAULT '0',
  last_stamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  rewarded SMALLINT NOT NULL DEFAULT '0'
);

CREATE UNIQUE INDEX player_passports_account_passport ON player_passports(account_id, passport_id);


-- Table structure for player_pets
DROP TABLE IF EXISTS player_pets CASCADE;
CREATE TABLE player_pets (
  player_id INTEGER NOT NULL,
  pet_id INTEGER NOT NULL,
  decoration INTEGER NOT NULL,
  name varchar(255) NOT NULL,
  hungry_level SMALLINT NOT NULL DEFAULT '0',
  feed_progress INTEGER NOT NULL DEFAULT '0',
  reuse_time BIGINT NOT NULL DEFAULT '0',
  birthday timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  mood_started BIGINT NOT NULL DEFAULT '0',
  counter INTEGER NOT NULL DEFAULT '0',
  mood_cd_started BIGINT NOT NULL DEFAULT '0',
  gift_cd_started BIGINT NOT NULL DEFAULT '0',
  dopings varchar(80) DEFAULT NULL,
  despawn_time timestamp NULL DEFAULT NULL,
  expire_time INTEGER NOT NULL,
  PRIMARY KEY (player_id, pet_id)
);


-- Table structure for player_punishments
DROP TABLE IF EXISTS player_punishments CASCADE;
CREATE TABLE player_punishments (
  player_id INTEGER NOT NULL,
  punishment_type VARCHAR(50) CHECK (punishment_type IN ('PRISON','GATHER','CHARBAN')) NOT NULL,
  start_time INTEGER DEFAULT '0',
  duration INTEGER DEFAULT '0',
  reason TEXT,
  PRIMARY KEY (player_id, punishment_type)
);


-- Table structure for player_quests
DROP TABLE IF EXISTS player_quests CASCADE;
CREATE TABLE player_quests (
  player_id INTEGER NOT NULL,
  quest_id INTEGER NOT NULL DEFAULT '0',
  status varchar(10) NOT NULL DEFAULT 'NONE',
  quest_vars INTEGER NOT NULL DEFAULT '0',
  complete_count INTEGER NOT NULL DEFAULT '0',
  complete_time timestamp NULL DEFAULT NULL,
  next_repeat_time timestamp NULL DEFAULT NULL,
  reward SMALLINT DEFAULT NULL,
  PRIMARY KEY (player_id, quest_id)
);


-- Table structure for player_recipes
DROP TABLE IF EXISTS player_recipes CASCADE;
CREATE TABLE player_recipes (
  player_id INTEGER NOT NULL,
  recipe_id INTEGER NOT NULL,
  PRIMARY KEY (player_id, recipe_id)
);


-- Table structure for player_registered_items
DROP TABLE IF EXISTS player_registered_items CASCADE;
CREATE TABLE player_registered_items (
  player_id INTEGER NOT NULL,
  item_unique_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  expire_time INTEGER DEFAULT NULL,
  color INTEGER DEFAULT NULL,
  color_expires INTEGER NOT NULL DEFAULT '0',
  owner_use_count INTEGER NOT NULL DEFAULT '0',
  visitor_use_count INTEGER NOT NULL DEFAULT '0',
  x REAL NOT NULL DEFAULT '0',
  y REAL NOT NULL DEFAULT '0',
  z REAL NOT NULL DEFAULT '0',
  h SMALLINT DEFAULT NULL,
  area VARCHAR(50) CHECK (area IN ('NONE','INTERIOR','EXTERIOR','ALL','DECOR')) NOT NULL DEFAULT 'NONE',
  floor SMALLINT NOT NULL DEFAULT '0',
  PRIMARY KEY (player_id, item_unique_id, item_id)
);


-- Table structure for player_settings
DROP TABLE IF EXISTS player_settings CASCADE;
CREATE TABLE player_settings (
  player_id INTEGER NOT NULL,
  settings_type SMALLINT NOT NULL,
  settings BYTEA NOT NULL,
  PRIMARY KEY (player_id, settings_type)
);


-- Table structure for player_shugo_sweep
CREATE TABLE player_shugo_sweep (
  player_id INTEGER NOT NULL,
  free_dice INTEGER NOT NULL DEFAULT '0',
  sweep_step INTEGER NOT NULL DEFAULT '0',
  board_id INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (player_id)
);


-- Table structure for player_skills
CREATE TABLE player_skills (
  player_id INTEGER NOT NULL,
  skill_id INTEGER NOT NULL,
  skill_level INTEGER NOT NULL DEFAULT '1',
  skin_id INTEGER DEFAULT '0',
  skin_active_date timestamp NULL DEFAULT NULL,
  skin_expire_time INTEGER DEFAULT NULL,
  skin_activated BIGINT NOT NULL DEFAULT '0',
  PRIMARY KEY (player_id, skill_id)
);


-- Table structure for player_skill_skins
DROP TABLE IF EXISTS player_skill_skins CASCADE;
CREATE TABLE player_skill_skins (
  player_id INTEGER DEFAULT '0',
  skin_id INTEGER DEFAULT '0',
  remaining BIGINT DEFAULT '0',
  active INTEGER DEFAULT '0',
  PRIMARY KEY (player_id, skin_id)
);


-- Table structure for player_stigmas_equipped
DROP TABLE IF EXISTS player_stigmas_equipped CASCADE;
CREATE TABLE player_stigmas_equipped (
  player_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  item_name varchar(100) DEFAULT NULL,
  PRIMARY KEY (player_id, item_id)
);


-- Table structure for player_thieves
DROP TABLE IF EXISTS player_thieves CASCADE;
CREATE TABLE player_thieves (
  player_id INTEGER NOT NULL,
  rank INTEGER NOT NULL DEFAULT '0',
  thieves_count INTEGER NOT NULL DEFAULT '0',
  prison_count INTEGER NOT NULL DEFAULT '0',
  last_kinah BIGINT NOT NULL DEFAULT '0',
  revenge_name varchar(25) NOT NULL DEFAULT 'Нет',
  revenge_count INTEGER NOT NULL DEFAULT '0',
  revenge_date timestamp NOT NULL DEFAULT '2016-07-30 00:00:00',
  PRIMARY KEY (player_id)
);

CREATE UNIQUE INDEX player_thieves_unique_name ON player_thieves(player_id);


-- Table structure for player_titles
DROP TABLE IF EXISTS player_titles CASCADE;
CREATE TABLE player_titles (
  player_id INTEGER NOT NULL,
  title_id INTEGER NOT NULL,
  remaining INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (player_id, title_id)
);


-- Table structure for player_transform
CREATE TABLE player_transform (
  player_id INTEGER NOT NULL,
  panel_id INTEGER NOT NULL DEFAULT '0',
  item_id INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (player_id, panel_id)
);


-- Table structure for player_upgrade_arcade
DROP TABLE IF EXISTS player_upgrade_arcade CASCADE;
CREATE TABLE player_upgrade_arcade (
  player_id INTEGER NOT NULL,
  frenzy_meter INTEGER NOT NULL,
  upgrade_lvl INTEGER NOT NULL,
  PRIMARY KEY (player_id)
);


-- Table structure for player_vars
DROP TABLE IF EXISTS player_vars CASCADE;
CREATE TABLE player_vars (
  player_id INTEGER NOT NULL,
  param varchar(255) NOT NULL,
  value varchar(255) DEFAULT NULL,
  "time" varchar(200) DEFAULT NULL,
  PRIMARY KEY (player_id, param)
);


-- Table structure for player_wardrobe
DROP TABLE IF EXISTS player_wardrobe CASCADE;
CREATE TABLE player_wardrobe (
  player_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  slot INTEGER NOT NULL,
  reskin_count INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (player_id, item_id)
);


-- Table structure for player_world_bans
DROP TABLE IF EXISTS player_world_bans CASCADE;
CREATE TABLE player_world_bans (
  player INTEGER NOT NULL,
  "by" varchar(255) NOT NULL,
  duration BIGINT NOT NULL,
  "date" BIGINT NOT NULL,
  reason varchar(255) NOT NULL,
  PRIMARY KEY (player)
);


-- Table structure for portal_cooldowns
DROP TABLE IF EXISTS portal_cooldowns CASCADE;
CREATE TABLE portal_cooldowns (
  player_id INTEGER NOT NULL,
  world_id INTEGER NOT NULL,
  reuse_time BIGINT NOT NULL,
  entry_count INTEGER NOT NULL,
  PRIMARY KEY (player_id, world_id)
);


-- Table structure for realms
DROP TABLE IF EXISTS realms CASCADE;
CREATE TABLE realms (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  name varchar(32) DEFAULT NULL,
  sqlhost varchar(32) DEFAULT NULL,
  sqluser varchar(32) DEFAULT NULL,
  sqlpass varchar(32) DEFAULT NULL,
  chardb varchar(32) DEFAULT NULL,
  PRIMARY KEY (id)
);


-- Table structure for server_variables
DROP TABLE IF EXISTS server_variables CASCADE;
CREATE TABLE server_variables (
  "key" varchar(30) NOT NULL,
  value varchar(30) NOT NULL,
  PRIMARY KEY (key)
);


-- Table structure for siege_locations
DROP TABLE IF EXISTS siege_locations CASCADE;
CREATE TABLE siege_locations (
  id INTEGER NOT NULL,
  race VARCHAR(50) CHECK (race IN ('ELYOS','ASMODIANS','BALAUR')) NOT NULL,
  legion_id INTEGER NOT NULL,
  occupy_count INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (id)
);


-- Table structure for skill_motions
DROP TABLE IF EXISTS skill_motions CASCADE;
CREATE TABLE skill_motions (
  motion_name varchar(255) NOT NULL DEFAULT '',
  skill_id INTEGER NOT NULL,
  attack_speed INTEGER NOT NULL,
  weapon_type varchar(255) NOT NULL,
  off_weapon_type varchar(255) NOT NULL,
  race varchar(255) NOT NULL,
  gender varchar(255) NOT NULL,
  "time" INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (motion_name, skill_id, attack_speed, weapon_type, off_weapon_type, gender)
);


-- Table structure for special_landing
CREATE TABLE special_landing (
  id INTEGER NOT NULL,
  type VARCHAR(50) CHECK (type IN ('ACTIVE','NO_ACTIVE')) NOT NULL,
  PRIMARY KEY (id)
);

-- Records of special_landing

-- Table structure for surveys
DROP TABLE IF EXISTS surveys CASCADE;
CREATE TABLE surveys (
  unique_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  owner_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  item_count decimal(20,0) NOT NULL DEFAULT '1',
  html_text TEXT NOT NULL,
  html_radio varchar(100) NOT NULL DEFAULT 'accept',
  used SMALLINT NOT NULL DEFAULT '0',
  used_time varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (unique_id)
);

CREATE INDEX idx_surveys_owner_id ON surveys(owner_id);


-- Table structure for tasks
DROP TABLE IF EXISTS tasks CASCADE;
CREATE TABLE tasks (
  id INTEGER NOT NULL,
  task_type VARCHAR(50) CHECK (task_type IN ('SHUTDOWN','RESTART')) NOT NULL,
  trigger_type VARCHAR(50) CHECK (trigger_type IN ('FIXED_IN_TIME')) NOT NULL,
  trigger_param TEXT NOT NULL,
  exec_param TEXT,
  PRIMARY KEY (id)
);


-- Table structure for threes_upgrade
DROP TABLE IF EXISTS threes_upgrade CASCADE;
CREATE TABLE threes_upgrade (
  id INTEGER NOT NULL,
  exp INTEGER NOT NULL DEFAULT '0',
  level INTEGER NOT NULL DEFAULT '1',
  threeId INTEGER NOT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX threes_upgrade_unique_id ON threes_upgrade(id);


-- Records

-- Table structure for towns
DROP TABLE IF EXISTS towns CASCADE;
CREATE TABLE towns (
  id INTEGER NOT NULL,
  level INTEGER NOT NULL DEFAULT '1',
  points INTEGER NOT NULL DEFAULT '0',
  race VARCHAR(50) CHECK (race IN ('ELYOS','ASMODIANS')) NOT NULL,
  level_up_date timestamp NOT NULL DEFAULT '2013-01-01 14:00:00',
  PRIMARY KEY (id)
);


-- Table structure for transaction_buy_history
DROP TABLE IF EXISTS transaction_buy_history CASCADE;
CREATE TABLE transaction_buy_history (
  id INTEGER NOT NULL,
  name varchar(255) DEFAULT NULL,
  price_id varchar(255) DEFAULT NULL,
  value varchar(255) DEFAULT NULL,
  "date" TIMESTAMP DEFAULT NULL
);


-- Table structure for transaction_convert_history
DROP TABLE IF EXISTS transaction_convert_history CASCADE;
CREATE TABLE transaction_convert_history (
  account_id INTEGER NOT NULL,
  player_id INTEGER DEFAULT NULL,
  player_name varchar(255) DEFAULT NULL,
  price_id BIGINT DEFAULT NULL,
  from_val BIGINT DEFAULT NULL,
  value BIGINT DEFAULT NULL,
  "date" timestamp NULL DEFAULT NULL,
  type varchar(255) DEFAULT 'NONE'
);


-- Table structure for users
DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
  account varchar(30) DEFAULT NULL,
  ip varchar(30) DEFAULT NULL,
  "date" TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (id)
);


-- Table structure for veteran_rewards
DROP TABLE IF EXISTS veteran_rewards CASCADE;
CREATE TABLE veteran_rewards (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  player varchar(255) NOT NULL,
  type INTEGER NOT NULL,
  item INTEGER NOT NULL,
  count INTEGER NOT NULL,
  kinah INTEGER NOT NULL,
  sender varchar(255) NOT NULL,
  title varchar(255) NOT NULL,
  message TEXT,
  PRIMARY KEY (id)
);


-- Table structure for weddings
CREATE TABLE weddings (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  player1 INTEGER NOT NULL,
  player2 INTEGER NOT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX idx_weddings_player1 ON weddings(player1);
CREATE INDEX idx_weddings_player2 ON weddings(player2);


-- Table structure for weddings_log
DROP TABLE IF EXISTS weddings_log CASCADE;
CREATE TABLE weddings_log (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  player_id INTEGER NOT NULL,
  partner_name TEXT,
  wedding_start timestamp NULL DEFAULT NULL,
  wedding_end timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);

